repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: mixed-line-ending
      - id: check-executables-have-shebangs

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/realm/SwiftLint
    rev: 0.57.0
    hooks:
      - id: swiftlint
        name: SwiftLint for Dripper package
        entry: swiftlint lint --config ".swiftlint.yml" "Sources/" "Examples"
        language: swift
        types: [swift]
        always_run: true
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.54.5
    hooks:
      - id: swiftformat
        name: SwiftFormat for Dripper package
        entry: swiftformat --config ".swiftformat" "Sources/" "Examples"
        language: swift
        types: [swift]
        always_run: true
